namespace Werewolves.Client.Testing;

public static class ModeratorUiTestIds
{
	public const string LandingShell = "landing-shell";
	public const string LandingContinueButton = "landing-continue-button";
	public const string LandingNewGameButton = "landing-new-game-button";
	public const string LandingNewGameCancel = "landing-new-game-cancel";
	public const string LandingNewGameConfirm = "landing-new-game-confirm";
	public const string LobbyRosterBack = "lobby-roster-back";
	public const string LobbyRosterReset = "lobby-roster-reset";
	public const string DashboardShell = "dashboard-shell";
	public const string DashboardCompactTabs = "dashboard-compact-tabs";
	public const string DashboardStatusBar = "dashboard-status-bar";
	public const string DashboardActionZone = "dashboard-action-zone";
	public const string InstructionBlock = "instruction-block";
	public const string SelectOptionsList = "select-options-list";
	public const string SelectOptionsOption = "select-options-option";
	public const string HoldButton = "hold-button";
	public const string AbandonGameButton = "abandon-game-button";
	public const string LobbyEvaluationPanel = "lobby-evaluation-panel";
	public const string LobbyEvaluationSummary = "lobby-evaluation-summary";
	public const string LobbyEvaluationDisclosure = "lobby-evaluation-disclosure";
	public const string LobbyEvaluationDetail = "lobby-evaluation-detail";
	public const string LobbyEvaluationRetry = "lobby-evaluation-retry";
	public const string LobbyEvaluationAsyncStatus = "lobby-evaluation-async-status";
	public const string LobbyEvaluationStatus = "lobby-evaluation-status";
	public const string LobbyEvaluationTurnEntry = "lobby-evaluation-turn-entry";
	public const string RoleSelectionStartGame = "role-selection-start-game";
	public const string RoleSelectionConfigureRoleLockIn = "role-selection-configure-role-lock-in";
	public const string RoleSelectionActionBar = "role-selection-action-bar";
	public const string RoleSelectionReset = "role-selection-reset";
	public const string ThiefRoleLockInPage = "thief-role-lock-in-page";
	public const string ThiefOffer1Options = "thief-offer-1-options";
	public const string ThiefOffer2Options = "thief-offer-2-options";
	public const string ThiefRoleLockInCommit = "thief-role-lock-in-commit";
	public const string ThiefRoleLockInBack = "thief-role-lock-in-back";
	public const string ThiefRoleLockInReview = "thief-role-lock-in-review";
	public const string ThiefRoleLockInSummary = "thief-role-lock-in-summary";
	public const string ActorSetupPage = "actor-setup-page";
	public const string ActorSetupList = "actor-setup-list";
	public const string ActorSetupCard = "actor-setup-card";
	public const string ActorSetupSelectionCount = "actor-setup-selection-count";
	public const string ActorSetupCommit = "actor-setup-commit";
	public const string ActorSetupBack = "actor-setup-back";
	public const string ActorSetupReview = "actor-setup-review";
	public const string ActorSetupSummary = "actor-setup-summary";
	public const string PublicGroupPartitionPage = "public-group-partition-page";
	public const string PublicGroupPartitionPlayerList = "public-group-partition-player-list";
	public const string PublicGroupPartitionPlayer = "public-group-partition-player";
	public const string PublicGroupPartitionFirstChoice = "public-group-partition-first-choice";
	public const string PublicGroupPartitionSecondChoice = "public-group-partition-second-choice";
	public const string PublicGroupPartitionCommit = "public-group-partition-commit";
	public const string PublicGroupPartitionBack = "public-group-partition-back";
	public const string PublicGroupPartitionReview = "public-group-partition-review";
	public const string PublicGroupPartitionSummary = "public-group-partition-summary";
}
